import { Geist, Geist_Mono } from "next/font/google";
import { Jost, DM_Serif_Display } from "@next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css"; // Import Remix Icon styles

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "700"], // Customize weights as needed
  variable: "--font-jost", // Custom variable for Tailwind
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dm-serif", // Custom variable for Tailwind
});

export const metadata = {
  title: "Interno",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} ${dmSerif.variable} antialiased bg-gray-100`}
      >
        {children}
      </body>
    </html>
  );
}
